import tree
import os
import torch
from tree import Tree, print_tree

thetree = Tree('<start>')
thetree.insert_son(0,'you')
thetree.insert_son(0,'banana')
thetree.make_index()
print_tree(thetree, True)
thetree.insert_son(0,'Maybe')
thetree.insert_son(0,'have')
thetree.make_index()
thetree.insert_son(4,'a')
thetree.insert_son(4,'.')
thetree.make_index()
print_tree(thetree, True)
thetree.insert_son(0,'<end>')
thetree.insert_son(0,'<end>')
thetree.insert_son(2,'<end>')
thetree.insert_son(2,'<end>')
thetree.insert_son(4,'<end>')
thetree.insert_son(4,'<end>')
thetree.insert_son(6,'<end>')
thetree.insert_son(6,'<end>')
thetree.make_index()
print_tree(thetree, True)

thetree2 = Tree('<start>')
thetree2.insert_son(0, 'have')
thetree2.insert_son(0, '.')
thetree2.make_index()
print_tree(thetree2, True)
thetree2.insert_son(0, 'I')
thetree2.insert_son(0, 'an')
thetree2.insert_son(2, 'apple')
thetree2.insert_son(2, '<end>')
thetree2.make_index()
print_tree(thetree2)
thetree2.insert_son(0, '<end>')
thetree2.insert_son(0, '<end>')
thetree2.insert_son(2, '<end>')
thetree2.insert_son(2, '<end>')
thetree2.insert_son(4, '<end>')
thetree2.insert_son(4, '<end>')
thetree2.make_index()
print_tree(thetree2, True)

torch.save([thetree, thetree2], os.path.join('fakedata', 'test_tree.txt'))